#ifndef HEADER_PBLAS_H
#define HEADER_PBLAS_H

/* defines
 */
#ifndef lapack_int
#define lapack_int int
#endif // lapack_int


/* Declarations
 */
extern void pcagemv_(const char* TRANS, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* BETA, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pdagemv_(const char* TRANS, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* BETA, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void psagemv_(const char* TRANS, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* BETA, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pzagemv_(const char* TRANS, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* BETA, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pcahemv_(const char* UPLO, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* BETA, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pzahemv_(const char* UPLO, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* BETA, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pcamax_(const lapack_int* N, float* AMAX, lapack_int* INDX, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pdamax_(const lapack_int* N, double* AMAX, lapack_int* INDX, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void psamax_(const lapack_int* N, float* AMAX, lapack_int* INDX, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pzamax_(const lapack_int* N, double* AMAX, lapack_int* INDX, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pdasum_(const lapack_int* N, double* ASUM, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void psasum_(const lapack_int* N, float* ASUM, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pdasymv_(const char* UPLO, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* BETA, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void psasymv_(const char* UPLO, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* BETA, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pcatrmv_(const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* BETA, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pdatrmv_(const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* BETA, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void psatrmv_(const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* BETA, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pzatrmv_(const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* BETA, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pcaxpy_(const lapack_int* N, const float* ALPHA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pdaxpy_(const lapack_int* N, const double* ALPHA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void psaxpy_(const lapack_int* N, const float* ALPHA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pzaxpy_(const lapack_int* N, const double* ALPHA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pscasum_(const lapack_int* N, float* ASUM, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pscnrm2_(const lapack_int* N, float* NORM2, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pccopy_(const lapack_int* N, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pdcopy_(const lapack_int* N, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void picopy_(const lapack_int* N, const lapack_int* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, lapack_int* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pscopy_(const lapack_int* N, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pzcopy_(const lapack_int* N, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pddot_(const lapack_int* N, double* DOT, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void psdot_(const lapack_int* N, float* DOT, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pcdotc_(const lapack_int* N, float* DOT, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pzdotc_(const lapack_int* N, double* DOT, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pcdotu_(const lapack_int* N, float* DOT, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pzdotu_(const lapack_int* N, double* DOT, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pzdscal_(const lapack_int* N, const double* ALPHA, double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pcgeadd_(const char* TRANS, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pdgeadd_(const char* TRANS, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void psgeadd_(const char* TRANS, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pzgeadd_(const char* TRANS, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pcgemm_(const char* TRANSA, const char* TRANSB, const lapack_int* M, const lapack_int* N, const lapack_int* K, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pdgemm_(const char* TRANSA, const char* TRANSB, const lapack_int* M, const lapack_int* N, const lapack_int* K, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void psgemm_(const char* TRANSA, const char* TRANSB, const lapack_int* M, const lapack_int* N, const lapack_int* K, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pzgemm_(const char* TRANSA, const char* TRANSB, const lapack_int* M, const lapack_int* N, const lapack_int* K, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pcgemv_(const char* TRANS, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* BETA, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pdgemv_(const char* TRANS, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* BETA, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void psgemv_(const char* TRANS, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* BETA, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pzgemv_(const char* TRANS, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* BETA, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pdger_(const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY, double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void psger_(const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY, float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pcgerc_(const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY, float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pzgerc_(const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY, double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pcgeru_(const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY, float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pzgeru_(const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY, double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pchemm_(const char* SIDE, const char* UPLO, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pzhemm_(const char* SIDE, const char* UPLO, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pchemv_(const char* UPLO, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* BETA, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pzhemv_(const char* UPLO, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* BETA, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pcher2_(const char* UPLO, const lapack_int* N, const float* ALPHA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY, float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pzher2_(const char* UPLO, const lapack_int* N, const double* ALPHA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY, double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pcher2k_(const char* UPLO, const char* TRANS, const lapack_int* N, const lapack_int* K, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pzher2k_(const char* UPLO, const char* TRANS, const lapack_int* N, const lapack_int* K, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pcher_(const char* UPLO, const lapack_int* N, const float* ALPHA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pzher_(const char* UPLO, const lapack_int* N, const double* ALPHA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pcherk_(const char* UPLO, const char* TRANS, const lapack_int* N, const lapack_int* K, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pzherk_(const char* UPLO, const char* TRANS, const lapack_int* N, const lapack_int* K, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pdnrm2_(const lapack_int* N, double* NORM2, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void psnrm2_(const lapack_int* N, float* NORM2, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pcscal_(const lapack_int* N, const float* ALPHA, float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pdscal_(const lapack_int* N, const double* ALPHA, double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void psscal_(const lapack_int* N, const float* ALPHA, float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pzscal_(const lapack_int* N, const double* ALPHA, double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pcsscal_(const lapack_int* N, const float* ALPHA, float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pcswap_(const lapack_int* N, float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pdswap_(const lapack_int* N, double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void psswap_(const lapack_int* N, float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pzswap_(const lapack_int* N, double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pcsymm_(const char* SIDE, const char* UPLO, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pdsymm_(const char* SIDE, const char* UPLO, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pssymm_(const char* SIDE, const char* UPLO, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pzsymm_(const char* SIDE, const char* UPLO, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pdsymv_(const char* UPLO, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* BETA, double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pssymv_(const char* UPLO, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* BETA, float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY);
extern void pdsyr2_(const char* UPLO, const lapack_int* N, const double* ALPHA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const double* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY, double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pssyr2_(const char* UPLO, const lapack_int* N, const float* ALPHA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, const float* Y, const lapack_int* IY, const lapack_int* JY, const lapack_int* DESCY, const lapack_int* INCY, float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pcsyr2k_(const char* UPLO, const char* TRANS, const lapack_int* N, const lapack_int* K, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pdsyr2k_(const char* UPLO, const char* TRANS, const lapack_int* N, const lapack_int* K, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pssyr2k_(const char* UPLO, const char* TRANS, const lapack_int* N, const lapack_int* K, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pzsyr2k_(const char* UPLO, const char* TRANS, const lapack_int* N, const lapack_int* K, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pdsyr_(const char* UPLO, const lapack_int* N, const double* ALPHA, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pssyr_(const char* UPLO, const lapack_int* N, const float* ALPHA, const float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX, float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA);
extern void pcsyrk_(const char* UPLO, const char* TRANS, const lapack_int* N, const lapack_int* K, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pdsyrk_(const char* UPLO, const char* TRANS, const lapack_int* N, const lapack_int* K, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pssyrk_(const char* UPLO, const char* TRANS, const lapack_int* N, const lapack_int* K, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pzsyrk_(const char* UPLO, const char* TRANS, const lapack_int* N, const lapack_int* K, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pctradd_(const char* UPLO, const char* TRANS, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pdtradd_(const char* UPLO, const char* TRANS, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pstradd_(const char* UPLO, const char* TRANS, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pztradd_(const char* UPLO, const char* TRANS, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pdtran_(const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pstran_(const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pctranc_(const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pztranc_(const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pctranu_(const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const float* BETA, float* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pztranu_(const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, const double* BETA, double* C, const lapack_int* IC, const lapack_int* JC, const lapack_int* DESCC);
extern void pctrmm_(const char* SIDE, const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, float* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB);
extern void pdtrmm_(const char* SIDE, const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, double* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB);
extern void pstrmm_(const char* SIDE, const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, float* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB);
extern void pztrmm_(const char* SIDE, const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, double* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB);
extern void pctrmv_(const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* N, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pdtrmv_(const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* N, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pstrmv_(const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* N, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pztrmv_(const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* N, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pctrsm_(const char* SIDE, const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, float* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB);
extern void pdtrsm_(const char* SIDE, const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, double* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB);
extern void pstrsm_(const char* SIDE, const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* M, const lapack_int* N, const float* ALPHA, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, float* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB);
extern void pztrsm_(const char* SIDE, const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* M, const lapack_int* N, const double* ALPHA, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, double* B, const lapack_int* IB, const lapack_int* JB, const lapack_int* DESCB);
extern void pctrsv_(const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* N, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pdtrsv_(const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* N, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pstrsv_(const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* N, const float* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, float* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pztrsv_(const char* UPLO, const char* TRANS, const char* DIAG, const lapack_int* N, const double* A, const lapack_int* IA, const lapack_int* JA, const lapack_int* DESCA, double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pdzasum_(const lapack_int* N, double* ASUM, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);
extern void pdznrm2_(const lapack_int* N, double* NORM2, const double* X, const lapack_int* IX, const lapack_int* JX, const lapack_int* DESCX, const lapack_int* INCX);

#endif // HEADER_PBLAS_H